# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodologias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='atividade_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeira_atividade', to='metodologias.Atividade'),
        ),
        migrations.AddField(
            model_name='metodologia',
            name='etapa_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeira_etapa', to='metodologias.Etapa'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapa_pai', to='metodologias.Etapa'),
        ),
    ]
