# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodologias', '0002_auto_20160916_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='metodologias.Etapa'),
        ),
    ]
