# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodologias', '0004_auto_20161016_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='metodologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='metodologias.Metodologia'),
        ),
    ]
