# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodologias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='metodologias.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('DE', 'Definido'), ('ES', 'Em espera'), ('EX', 'Em Execução'), ('CO', 'Concluído')], default='DE', max_length=2)),
                ('imagem_capa', models.ImageField(default='static/img/projetos/capas/default.png', upload_to='static/img/projetos/capas/')),
                ('metodologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metodologias.Metodologia')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='execucao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='projetos.Projeto'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='projetos.Recurso'),
        ),
    ]
