# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodologias', '0003_auto_20160921_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('DE', 'Definido'), ('ES', 'Em espera'), ('EX', 'Em Execução'), ('CO', 'Concluído')], default='DE', max_length=2)),
                ('metodologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metodologias.Metodologia')),
            ],
        ),
    ]
