# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem_capa',
            field=models.ImageField(default='static/img/projetos/capas/default.png', upload_to='static/img/projetos/capas/'),
        ),
    ]
