# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='projetos.Recurso'),
        ),
    ]
