# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20161126_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='metodologia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metodologias.Metodologia'),
        ),
    ]
