# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20161127_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem_capa',
            field=models.ImageField(upload_to='static/img/projetos/capas/'),
        ),
    ]
