# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodologias', '0006_auto_20161017_2213'),
        ('projetos', '0003_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='metodologias.Atividade')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='projetos.Projeto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='projetos.Recurso')),
            ],
        ),
    ]
