# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.Recurso')),
            ],
        ),
    ]
