# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto',
            name='recurso',
        ),
        migrations.AddField(
            model_name='texto',
            name='execucao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='editor', to='projetos.Execucao'),
            preserve_default=False,
        ),
    ]
