# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_recurso'),
        ('editor', '0002_remove_editor_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projetos.Recurso')),
                ('conteudo', models.TextField()),
            ],
            bases=('projetos.recurso',),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
