# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20161123_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='execucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='projetos.Execucao'),
        ),
    ]
