# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20161127_0205'),
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='recurso',
        ),
        migrations.AddField(
            model_name='galeria',
            name='execucao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='projetos.Execucao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(default='static/img/projetos/capas/default.png', upload_to='static/img/projetos/galeria/'),
        ),
    ]
