# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_recurso'),
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='id',
        ),
        migrations.AddField(
            model_name='galeria',
            name='recurso_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projetos.Recurso'),
            preserve_default=False,
        ),
    ]
