# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20161104_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(default='static/img/projetos/capas/default.png', upload_to='static/img/galeria/')),
            ],
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='foto',
        ),
        migrations.AddField(
            model_name='imagem',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='galeria.Galeria'),
        ),
    ]
