# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170308_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
