# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170308_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='send_date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='invite',
            name='unsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='invite',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
